export const FEATURE_MENU_ITEMS = [
  {
    label: "Direct RPC",
    href: "#direct-rpc",
    desc: "zero-hop gRPC, mTLS, round-robin",
    iconName: "Zap",
    iconColor: "text-blue-400",
    iconBg: "bg-blue-500/10",
  },
  {
    label: "HTTP Middleware",
    href: "#http",
    desc: "Express, Fastify, Gin, FastAPI auto-trace",
    iconName: "Globe",
    iconColor: "text-indigo-400",
    iconBg: "bg-indigo-500/10",
  },
  {
    label: "Durable Events",
    href: "#durable-events",
    desc: "fan-out, retries, DLQ, replay",
    iconName: "Radio",
    iconColor: "text-emerald-400",
    iconBg: "bg-emerald-500/10",
  },
  {
    label: "Realtime Streams",
    href: "#streams",
    desc: "live chunks with replay",
    iconName: "Waves",
    iconColor: "text-red-400",
    iconBg: "bg-red-500/10",
  },
  {
    label: "Workflows",
    href: "#workflows",
    desc: "parallel DAG, conditions, sleep, event wait",
    iconName: "Workflow",
    iconColor: "text-fuchsia-400",
    iconBg: "bg-fuchsia-500/10",
  },
  {
    label: "Jobs",
    href: "#jobs",
    desc: "cron, delayed, workflow-triggered",
    iconName: "Clock",
    iconColor: "text-amber-400",
    iconBg: "bg-amber-500/10",
  },
  {
    label: "Discovery + Maps",
    href: "#service-discovery",
    desc: "O(1) lookup, service map, connections",
    iconName: "Network",
    iconColor: "text-cyan-400",
    iconBg: "bg-cyan-500/10",
  },
  {
    label: "Unified Tracing",
    href: "#tracing",
    desc: "waterfall per request, retries, fan-out",
    iconName: "Activity",
    iconColor: "text-sky-400",
    iconBg: "bg-sky-500/10",
  },
  {
    label: "Metrics & Logs",
    href: "#observability",
    desc: "Prometheus /metrics, Loki-compatible API",
    iconName: "BarChart2",
    iconColor: "text-orange-400",
    iconBg: "bg-orange-500/10",
  },
  {
    label: "Smart Alerts",
    href: "#alerts",
    desc: "telegram, webhook, in-app",
    iconName: "AlertTriangle",
    iconColor: "text-rose-400",
    iconBg: "bg-rose-500/10",
  },
] as const;
